# -*- coding: utf-8 -*-
"""RC_phase_shift_oscillator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iH6JlxxIdMkLgmWOojZxI4DsmEenu_6p
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
# %config InlineBackend.figure_format = 'svg'

import schemdraw
import schemdraw.logic as logic
import schemdraw.elements as elm


d = schemdraw.Drawing()
op = d.add(elm.Opamp)
d.add(elm.Line('left', xy=op.in2, l=d.unit/4))
d.add(elm.Line('down', l=d.unit/5))
d.add(elm.Ground)
d.add(elm.Line('left', xy=op.in1, l=d.unit/6))
d.add(elm.Dot)
d.push()
Rin = d.add(elm.Resistor('left', xy=op.in1, botlabel='$10k\Omega$'))
d.pop()
d.add(elm.Line('up', l=d.unit/2))
Rf = d.add(elm.Resistor('right', l=d.unit*1, label='$290K\Omega$'))
d.add(elm.Line('down', toy=op.out))
d.add(elm.Dot)
d.add(elm.Line('left', tox=op.out))
d.add(elm.Line('right', l=d.unit/4 ))
C_1 = d.add(elm.Capacitor('right', l=d.unit, label='$0.001\mu F$'))
R_1 = d.add(elm.Resistor('down', label='$10k\Omega$'))
d.add(elm.Ground)
C_2 = d.add(elm.Capacitor('right', xy=R_1.start, label='$0.001\mu F$'))
R_2 = d.add(elm.Resistor('down', label='$10k\Omega$'))
d.add(elm.Ground)
C_3 = d.add(elm.Capacitor('right', xy=R_2.start, label='$0.001\mu F$'))
d.add(elm.Line('right',xy=C_3.end, l=d.unit/3, label='$V_o$'))
d.add(elm.Line('down', xy=Rin.end, l=d.unit*1.6))
d.add(elm.Line('right', l=d.unit*5))
d.add(elm.Line('up', l=d.unit*1.4))
d.add(elm.Dot)
d.draw()


d.save('RC_Phase_Shift_Oscillator.pdf')

